### ISSUE TITLE
Clean interface

### ISSUE THREAD

**Issue by bezoerb** [bezoerb/filter-css#1]
Instead of specifying the different filter levels like that:

``` js
filterCss('test/fixtures/test.css', {
    types: ['@font-face'],
    selectors: ['.my-selector > p'],
    declarations: [/url/]
});
```

it could be more intuitive to specify filter levels like that:

``` js
filterCss('test/fixtures/test.css', [<string or regex>,...], {
  matchDeclarationProperties: true,
  matchDeclarationValues: true,
  matchTypes: true,
  matchSelectors: true,
  ...
});
```

**Comment by rupl** [comment]
I actually think the first example makes more sense. Specifying each class of filter as obj prop is simple and very easy to understand when reading. My confusion stemmed from the fact that I was looking at simpler examples that only used one (e.g. only types, or only declarations). But I think having a few more examples would clear up most confusion.

Is there a technical advantage to your second example here? I can imagine where it might be slightly more brittle or even impossible to set up a filter using the boolean props.

For instance, I might have:
- a `.url` class that I **don't** want filtered
- a `.header` class that should be filtered
- a `url` value that should be filtered

If that were the case, I'd be doing something like this:

``` js
filterCss('test/fixtures/test.css', [/url/, '.header'], {
  matchDeclarationValues: true,
  matchSelectors: true
}
```

...which will filter out all three. I might be missing something but the individual definitions make more sense in my head.

**Comment by bezoerb** [comment]
@rupl thanks a lot for your thoughts ;)
I had some use-case like the one mentioned in my head when i initially chose the first syntax. 
This one get's very unhandy if you want to filter a lot of different types. Then you'll have to use a lot of different object props. e.g.

``` js
filterCss('test/fixtures/test.css', {
    types: ['@font-face'],
    media: [/print/], // not implemented yet
    selectors: ['.my-selector > p'],
    declarations: [/url/],
    declarationProperties: ['background-image'] // not implemented yet
});
```

The times where selector names and declarations overlap, are negligible in my opinion and I'm not sure whether the more complex syntax is worth it. Your example could be solved like this 

``` js
filterCss('test/fixtures/test.css', [/url\(/, '.header']) 
```

which is much nicer to write than

``` js
filterCss('test/fixtures/test.css', {
    selectors: ['.header'],
    declarations: [/url/]
})
```

Additionally it would be still possible to use a function as ignore statement to have a more fine grained control about what get's dropped.

something like that for example:

``` js
filterCss('test/fixtures/test.css', ['.header',function(...){
}]) 
```

or 

``` js
filterCss('test/fixtures/test.css',function(...){
}) 
```

**Comment by bezoerb** [comment]
@addyosmani with this module finding it's way to `critical` you might be interested in adding some thoughts, too? ;)

**Comment by rupl** [comment]
I don't actually have a problem with that first syntax you mentioned in https://github.com/bezoerb/filter-css/issues/1#issuecomment-102860850 but hey it's just my opinion.

I concede that the situation I described is a bit contrived :grin:  There are relatively few situations where someone uses a class that matches a value substring. In the end I will be very happy to see any capability added to `critical` so if you think one or the other is more flexible I am :cool: with it.

**Comment by bezoerb** [comment]
Fixed by https://github.com/bezoerb/filter-css/commit/eca4075639fa8d22ead09c81c55066524479faaa

**Comment by rupl** [comment]
:tada: :confetti_ball: you rock!
